version: "3.5"

services:
  app:
    image: tranthaison1231/discord-api:latest
    build:
      context: .
    container_name: discord-api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
